src/js/l.control.geosearch.js

This minor change avoids the need for querying by element id, since the query input box is already stored on the instance as `this._searchbox`. All the element ids can be removed, but I left them as they are in case people are using ids for styling.

Support for multiple maps on page

---

src/js/l.control.geosearch.js

This method is unsupported in older browsers.
Replaced with use of 'that' in callback.

Replaced .bind in geosearch

---

readme.md
src/js/l.control.geosearch.js

This PR introduces a way to retain the zoom-level of the map you are in. This retaining will of course only be used when the appropriate configuration is set.
You can configure GeoSearch by adding ```retainZoomLevel``` to the config-options like follows:
new L.Control.GeoSearch({
provider: new L.GeoSearch.Provider.OpenStreetMap(),
retainZoomLevel: true,
}).addTo(map);
Setting ```retainZoomLevel``` to ```true``` will not change the zoom-level the user is currently in when centering the map on the new coordinates. Setting it to ```false``` (which is the default) will keep the current behaviour that changes the zoom-level to a fixed value (by default ```18```)
So Backwards-Compatibility is given, it justs adds the posibility to keep the current zoom-level

Retain zoomLevel when centering map

---

src/js/l.control.geosearch.js

I think it would be great if the user could locate a place with the geosearch plugin and then modify it with the snap plugin for example (At least it would be great for my needs)
To achieve that, i've just added the marker object to the data sent within the showlocation event.
I know it's not perfect and that it sends undefined if the show marker option is set to false, but I think it's better than sending nothing in that case, because if the rest of the app isn't well coded, the whole script could crash because it tries to access to an value which doesn't exists

Sending the marker within the showlocation event

---

src/js/l.control.geosearch.js

1) after pressing <enter> in the searchbox, do event.preventDefault and event.stopPropagation to prevent submit forms to be submitted. Fixes #12 
2) add option "draggable", so the marker can be drag/dropped after a search has been done.

event.preventDefault for searchbox on enter. option "draggable"

---

src/js/l.control.geosearch.js
src/js/l.geosearch.provider.openstreetmap.js

With OSM by passing {addressdetails: 1} when initializing the provider, you can get back specific details on the different elements of the result address (like postal code etc).
This change exposes those details to the end dev in the details property of search result's Location. I only took the time to implement this for OSM for now, maybe others can help by doing the same for other providers.
I'm also constructing bounds to be passed back to the map.

Improved OSM support

---

src/js/l.control.geosearch.js

- When 'retainZoomLevel' is set to true, _getZoomLevel returns zoom of map.
- Whereas there is no such property as 'zoom' for map and hence undefined is returned.
- Correct property is '_zoom' which should be returned to make zoom work fine when retainZoomLevel is set to true.
- Refer the Leaflet source code (getZoom function).

Returns valid map property (_zoom). Fixes #65

---

src/js/l.control.geosearch.js

This pull request is based on #64 (and thus closes #64 if accepted).
It also adds a new option `showPopup` (`false` by default). If it is set to `true`, then after each successful search a popup appears above the resulting marker; that popup contains a copy of the search query.
If there are many markers on the map, such popup helps users to identify search results. (It might be quite useful to change the results' marker as well, and that's exactly why this pull request is based on #64.)

show a popup after a search is completed successfully

---

src/js/l.geosearch.provider.google.js

If the the Google Maps API is already loaded, we still need to populate the leaflet data provider.  This should take care of that.

Fixing bug when Maps API already loaded

---

readme.md

According the [referece](http://leafletjs.com/reference.html#control) control has only ``topleft`` and ``topright``. Probably ``topcenter`` is typo?

Updated usage on frontpage

---

readme.md

The unpkg repo URL doesn't function without trailing slash.

update readme.md unpkg repo url

---

src/leafletControl.js
src/providers/locationIQProvider.js
src/providers/openStreetMapProvider.js

See #144 for discussion
I have not tested this, I don't have a proper dev environment to be able to build.
Overview of the changes:
- Add a `data` argument for searching, it should get ignored as-is for other providers, it's only handled by the `search` function overridden for the OSM and LocationIQ providers.
- Add the result from the previous search as the `data` when handling the click on the result list.
- Add the result from the previous search as the `data` when hitting `ENTER` when an item in the result list is selected. For this, I moved up the `const list` to before the check for the `ENTER` key, and I call `select()` on the currently selected item to get the result data.
- Add `endpointReverse` which fills in the params for the `reverse` API endpoint, i.e. the `osm_id` and …

Fix failing search for OSM and LocationIQ, fix #144

---

src/resultList.js

This bug is triggered by typing a word and hitting enter before the AJAX request returns (depends on internet connection speed).
This fixes the TypeError raised when the results list is still undefined. `this.results` isn't initialised with a default value. When an enter key is hit within a search box, it triggers the `select` method (even if there are no results to select). When `select` references `this.results`, it's still undefined.

Stop enter key triggering TypeError in search box (issue #181)

---

src/providers/__tests__/googleProvider.spec.js

API Key is required now
- add an API key from env to provider in tests
- remove a test, related to fetching with API key
(fetching with key by default)

Fix for google provider test

---

src/domUtils.js
src/leafletControl.js
src/searchElement.js

Hi, 
I have added an option "stopClickPropagation" to stop propagation on click to allow people to be able to use something like map.on('click', function() { alert("Click") }); and not have it trigger on clicking the search form. 
I have also added autocomplete="none" to the search form due to web browsers trying to autocomplete and hiding the search results.
Not sure if you want these commits but I thought I would chuck them your way :)

Adding option to stop propagation and add autocomplete=none to search form

---

src/SearchControl.ts

**Problem:**
current code fails on leaflet 1.7+ when you try to search more than once with error `leaflet-src.js:69 Uncaught (in promise) TypeError: Cannot create property '_leaflet_id' on string '582'` because [now](https://github.com/Leaflet/Leaflet/pull/6998/files) leaflet doesn't support number-like strings. It was missed since TypeScript was suppressed here.
**Proposed changes:**
1. use `getLayers` function instead of a private field
2. Remove ts suppression

fix: use marker layer instead of layer key

---

README.md
src/SearchControl.ts

@smeijer & maintainers I have a Pull Request for your review.
For the Leaflet SearchControl I've added an `updateMap` option to not center the map at all.
This is a very useful option because it works well in conjunction with the `geosearch/showlocation` event. It frees up developers to use the convenience of the built-in Leaflet Control without restricting them to forced map centering.
I have a use-case for an app I'm building where instead of moving the map to the specific location searched, I will use the location from the event to instead zoom to the county that the location is in. This feature would give me the freedom to use your Leaflet Control while writing my own map centering.
I hope you like this feature and please let me know if there's anything I can/should change. I picked …

feat: add leaflet control option to not update map view

---

README.md
package.json
src/SearchControl.ts
src/resultList.ts

Some search providers, especially OSM, return the address search results in a not very common order.
E. g. the house number is returned in the first position of the label, which is very uncommon in German.
This PR introduces a callback function which is executed in order to manipulate the search result label.
As the query is currently not available in the result list, it could not be propagated to the callback function.
Adding this would have increased the PR which I wanted to avoid.
Provider OSM
with callback injected
```javascript
resultFormat: (result)=>{
if(result.label.match(/^\d+,/)){
// swap house no and street
const components = result.label.split(',').map(s=>s.trim())
const houseNo = components[0]
components[0] = components[1]
components[1] = houseNo
return …
```

feat: add option to format results

---

src/SearchControl.ts

Hello,
Whether or not this is actually needed or how it is implemented depends on the intended functionality, but I ran into an issue where it was impossible for me to get my zoomLevel option to affect anything when creating a new instance of GeoSearchControl. This was because I was using the HereProvider, and HereAPI does not return bounds. The provider returns null for result.bounds. Because result.bounds is null, this causes the first if statement in SearchControl.centerMap() to always evaluate to true, which disregards the zoomLevel option and uses const resultBounds, which in the case of hereAPI always evaluates to 'new L.LatLng(result.y, result.x).toBounds(10)' because result.bounds is null with HereProvider.
This effectively makes it so that you can never go by options.zoomLevel …

fix: support retainZoomLevel for providers not including bounds

---

src/index.ts
src/providers/index.ts
src/providers/mapBoxProvider.ts

Added new MapBox provider for GeoSearch.
example of usage:
`      const provider = new MapBoxProvider({
params: {
access_token:
"ACCESS_TOKEN",
},
});`
An access token can be obtained here:
https://docs.mapbox.com/accounts/overview/tokens/

feat: add MapBox provider

---

README.md
docs/lib/providers.ts
docs/providers/geoapifr.mdx
src/index.ts
src/providers/geoApiFrProvider.ts
src/providers/index.ts

Add proposed provider by @taiebnoe in [Discussions](https://github.com/smeijer/leaflet-geosearch/discussions/268), this is the French Adress API Provider.
Add a new provider for french adresse given by the french governement : 
https://geo.api.gouv.fr/adresse

feat: add GeoApiFR provider

---

package.json

Fix `DEP0148: Folder mappings in "exports" (trailing "/")` using Node.js 16

fix #286 - DeprecationWarning DEP0148

---

assets/css/leaflet.css
docs/leaflet-control.mdx
src/SearchControl.ts
src/resultList.ts

Fix #282 Display not found message
The properties notFoundMessage isn't used in the lib.
If there are 0 result and the notFountMessage is setted, display the message : 
In the resultList class, classNames isn't filled.
Add two new properties in the classNames config : 
- resultlist : class for style the result list
- item : class for style items in the result list
- notfound : class for style when no results (by default use italic tests)
By default, the config option notFoundMessage as the default unused value : 'Sorry, that address could not be found.',
Does change it to default to empty, to keep the same behavior as now ?

feat: add option for custom "not found message"

---

docs/leaflet-control.mdx
docs/providers/algolia.mdx
docs/providers/bing.mdx
docs/providers/esri.mdx
docs/providers/geoapifr.mdx
docs/providers/geocode-earth.mdx
docs/providers/google.mdx
docs/providers/here.mdx
docs/providers/locationIq.mdx
docs/providers/opencage.mdx
docs/providers/openstreetmap.mdx
docs/providers/pelias.mdx
docs/usage.mdx

By default, many of the Playground maps use the 'bar' style
search control, but the code examples associated with the maps
do not specify the style. This ends up rendering a map with a
button-style control, which does not match the example maps.
This commit updates the documentation to specify `style: 'bar'`
whenever the associated example map is using a bar.

docs: make code examples consistent with map examples

---

.github/workflows/ci.yml
src/SearchControl.ts
src/__tests__/SearchControl.spec.js

hi,
this should fix failures in combination with leaflet-1.8.0.
It is required as a workaround since https://github.com/Leaflet/Leaflet/pull/7459 landed in leaflet.
I am not very familiar with the github workflow system, thus the ci commit might not be the correct solution,
consider it as a rfc. There might be a better solution I am not aware of.
BR,
Valentin Kunz

fix: add support for leaflet 1.8.0

---

assets/css/leaflet.css

fix: set height of search box to match surrounding boxes

---

src/providers/openStreetMapProvider.ts

See #355. That pull got merged in the wrong branch.

fix: OpenStreetMap named their prop licence, not license.

---

assets/css/leaflet.css

Minor changes to centre the magnifying glass icon and stop it moving around when clicking the button.
I've tested this on a few different browsers across several OSs (Win10, MacOS, IOS, Android), hopefully that's sufficient.

fix: button styling improvements

---

package.json

fix #370
If it's not too much trouble, could you please add the `hacktoberfest-accepted` tag to this PR?

fix error when importing leaflet-geosearch using TypeScript

---

src/SearchControl.ts
src/coords.ts

Quick, *pure js* implementation to handle coordinate queries (#147). If a user enters valid coordinates, they get a single result with that point (as in Google Maps and other services). It's a useful feature for power users.
Any other queries are sent to the Provider. Happy to see this in TypeScript and otherwise improved, it's probably not ready for merging.

Add handling of lat, lon coordinate queries

---

src/providers/locationIQProvider.ts

Location IQ throws a 404 error when it is unable to locate any match.  such as when typing "san Angl" and there are no places that begin with that string.  To repair, the parse method checks for the `response.data.error` in the response, returns an empty string if it has an error, and otherwise, hands back up to the parent class.  
I am new to this library (and not a typescript expert), so while I believe this works, if there is a better way to handle errors, happy to learn!

fix: ensure remote errors in LocationIQ Provider are handled

---

docs/introduction.mdx

I kept getting a `TypeError i is undefined` with the umd version of the script from unpkg. I finally found issue #92 and someone suggested using a different version on unpkg. I tried that and my error was resolved so I made that change in the docs.

chore: update introduction.mdx

---

src/providers/algoliaProvider.ts
src/providers/esriProvider.ts

Added exports to types that are commonly used outside of the lib.

feat: export ersi and algolia result types

---

src/providers/googleProvider.ts

Exported the missing types that are commonly used when using the google provider.

Export google provider types

---

src/providers/hereProvider.ts

The Here service API URL is wrong. It only needs one word change to make it work properly.

fix: change URL of Here API

---

README.md

Followed the provided example to use with react-leaflet and noticed a css import was missing.

Update README.md to include missing CSS import.

---

docs/usage.mdx
src/SearchControl.ts

Fixes #380
Add `resetButton` option to `GeoSearchControl` to allow changing the cross icon.
* Add `resetButton` option to `SearchControlProps` interface in `src/SearchControl.ts`.
* Update `defaultOptions` to include `resetButton` with default value '×' in `src/SearchControl.ts`.
* Update `resetButton` element creation to use `resetButton` option value in `src/SearchControl.ts`.
* Add documentation for `resetButton` option in the `GeoSearchControl` section in `docs/usage.mdx`.

feat: change icon in search control reset button

---

src/providers/openCageProvider.ts

This change prevents the plugin to thow an error when the `bounds` attribute is absent from the API result
✅ Closes: #421

fix: 🐛 prevent error with no bounds attribute
