package.json, src/js/l.geosearch.provider.google.js
=> Check if GMaps API avail before loading. Fixes smeijer/L.GeoSearch#51

src/js/l.control.geosearch.js, src/js/l.geosearch.provider.esri.js, src/js/l.geosearch.provider.google.js, src/js/l.geosearch.provider.openstreetmap.js
=> update to new GH url

example/bing.html, example/esri.html, example/google.html, example/nokia.html, example/openstreetmap.html, readme.md, src/js/l.control.geosearch.js, src/js/l.geosearch.provider.google.js
Due to cloudmade discontinuing their MapTile service for
non-enterprise users.
Fixes issue 41
=> Changed cloudmade tile url to OSM tile provider

readme.md
enables syntax highlighter, making the whole thing easier to read and beautiful :)
=> specifying the language used in code blocks

src/js/l.control.geosearch.js
This little change allows me to pass in a custom icon with the geosearch creation so that I can customize the icon.
=> Custom icon option for marker.

src/js/l.geosearch.provider.google.js
=> Add google maps key option

readme.md
Search input label was missing from the documentation
=> Add search label to documentation

readme.md, src/leafletControl.js, src/resultList.js
Adds a new option called 'autoClose' which hides the result
list when a result is choosen. Additionally, it wires the
'Enter' key to select a result, too.
closes #103
=> Auto close feature

src/leafletControl.js
Prevent empty search requests when removing search query with backspace
=> Prevent empty search requests

readme.md, src/leafletControl.js
Allow users to customize popup text
=> Add popupFormat option to GeoSearchControl

readme.md, src/leafletControl.js
Fire event with location and event arguments after marker has been
dragged. Resolves #71
=> Fire event after dragging the marker

.gitignore, lib/constants.js, lib/domUtils.js, lib/index.js, lib/leafletControl.js, lib/providers/bingProvider.js, lib/providers/esriProvider.js, lib/providers/googleProvider.js, lib/providers/index.js, lib/providers/openStreetMapProvider.js, lib/providers/provider.js, lib/resultList.js, lib/searchElement.js, readme.md, src/leafletControl.js
=> Additional option "keepResults"

src/leafletControl.js
=> Select of search item using arrow keys and enter button

src/leafletControl.js
=> Disable click propagation of search element

readme.md
Resolve https://github.com/smeijer/leaflet-geosearch/issues/135#issuecomment-520036544
=> Update `readme.md` with typescript info #135 

src/providers/algoliaProvider.ts
=> feat: improve labels of Algolia provider by using match level

src/SearchControl.ts
For historical reasons, we had our own way to stop event propagation to leaflet. However, things have changed and after the v3 release, click handlers weren't properly restored.
Besides, the custom propagation handlers are no longer required. I've removed those, and added a few leaflet methods to stop propagation instead. 
---
fixes #223
=> fix: leaflet map handlers weren't restored properly

src/resultList.ts
It's more like proposal, rather than "feature" :)
Almost all completion fields on websites are working in the way, when suggestion list is closing after select.
Old behavior: https://streamable.com/cuvm9l
New behavior: https://streamable.com/jxtolu
=> Close completion list after select

package.json
=> fix: update types path

src/SearchControl.ts
I had an issue with the migration between different versions on angular 12 application
=> chore: use * import from leaflet

src/SearchControl.ts, src/resultList.ts
=> Results list now clears when pressing enter

src/coords.ts
Fixes smeijer/leaflet-geosearch#382
=> Prevent TypeError: t.trim is not a function

src/index.ts, src/providers/civilDefenseMapProvider.ts, src/providers/index.ts
We develop new provider based on the data from [RÚIAN](https://www.cuzk.cz/ruian/RUIAN.aspx) service, which are intended for the Czech Republic. We would like to put our work into upstream. For any questions, please write to David Barina <ibarina@fit.vutbr.cz>. Thank you.
=> feat: add provider for https://civildefense.fit.vutbr.cz/search

docs/components/Map.tsx, docs/introduction.mdx
https://github.com/openstreetmap/operations/issues/737
=> chore(tile-service): Use tile.openstreetmap.org without subdomains
